Use specific version of Cake.Incubator
As newer version fails with error `error CS1061: 'GitVersion' does not contain a definition for 'Dump' and no extension method 'Dump' accepting a first argument of type 'GitVersion' could be found (are you missing a using directive or an assembly reference?)`